### ISSUE TITLE
SyntaxWarning: 'int' object is not callable in SystemFlags.py

### ISSUE THREAD

**Issue by elboulangero** [p0dalirius/pydsinternals#9]
When I install the package in Kali Linux, there are a lot of errors:

```
Setting up python3-dsinternals (1.2.4+git20220411-0kali1) ...
/usr/lib/python3/dist-packages/dsinternals/datastore/SystemFlags.py:21: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  1 (0x00000001)
/usr/lib/python3/dist-packages/dsinternals/datastore/SystemFlags.py:25: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  2 (0x00000002)
/usr/lib/python3/dist-packages/dsinternals/datastore/SystemFlags.py:28: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  4 (0x00000004)
/usr/lib/python3/dist-packages/dsinternals/datastore/SystemFlags.py:31: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  16 (0x00000010)
/usr/lib/python3/dist-packages/dsinternals/datastore/SystemFlags.py:34: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  33554432 (0x02000000)
/usr/lib/python3/dist-packages/dsinternals/datastore/SystemFlags.py:37: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  67108864 (0x04000000)
/usr/lib/python3/dist-packages/dsinternals/datastore/SystemFlags.py:40: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  134217728 (0x08000000)
/usr/lib/python3/dist-packages/dsinternals/datastore/SystemFlags.py:43: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  268435456 (0x10000000)
/usr/lib/python3/dist-packages/dsinternals/datastore/SystemFlags.py:46: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  536870912 (0x20000000)
/usr/lib/python3/dist-packages/dsinternals/datastore/SystemFlags.py:49: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  1073741824 (0x40000000)
/usr/lib/python3/dist-packages/dsinternals/datastore/SystemFlags.py:52: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  2147483648 (0x80000000)
```

At first I thought it was due to a change in Python 3.11. But I tried with Python 3.9, and the syntax is not valid either. Minimal way to reproduce is (ie. I just take the first lines from https://github.com/p0dalirius/pydsinternals/blob/main/dsinternals/datastore/SystemFlags.py):

```
# python3 -c "
from enum import Enum
class SystemFlags(Enum):
    1 (0x00000001)
"
<string>:4: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "<string>", line 4, in SystemFlags
TypeError: 'int' object is not callable
```

Is it intended, is the file `SystemFlags.py` used in a special way, or is it really just wrong syntax?

Thanks!

**Comment by p0dalirius** [comment]
It was bad syntax, I forgot this file, sorry.

Best regards,

**Comment by elboulangero** [comment]
Thanks for the quick fix!
